# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect,
                            QSize, Qt)
from PySide6.QtGui import (QAction, QFont, QIcon)
from PySide6.QtWidgets import (QLabel, QMenu,
                               QMenuBar, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QSize(1280, 720))
        MainWindow.setMaximumSize(QSize(1280, 720))
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.Computer))
        MainWindow.setWindowIcon(icon)
        self.action_balise_create = QAction(MainWindow)
        self.action_balise_create.setObjectName(u"action_balise_create")
        self.action_log_save = QAction(MainWindow)
        self.action_log_save.setObjectName(u"action_log_save")
        self.action_config_save = QAction(MainWindow)
        self.action_config_save.setObjectName(u"action_config_save")
        self.action_train_create = QAction(MainWindow)
        self.action_train_create.setObjectName(u"action_train_create")
        self.action_run = QAction(MainWindow)
        self.action_run.setObjectName(u"action_run")
        self.action_stop = QAction(MainWindow)
        self.action_stop.setObjectName(u"action_stop")
        self.action_pause = QAction(MainWindow)
        self.action_pause.setObjectName(u"action_pause")
        self.action_station_create = QAction(MainWindow)
        self.action_station_create.setObjectName(u"action_station_create")
        self.actionbalise0_config = QAction(MainWindow)
        self.actionbalise0_config.setObjectName(u"actionbalise0_config")
        self.actionbalise0_del = QAction(MainWindow)
        self.actionbalise0_del.setObjectName(u"actionbalise0_del")
        self.actionbalise1_config = QAction(MainWindow)
        self.actionbalise1_config.setObjectName(u"actionbalise1_config")
        self.actionbalise1_del = QAction(MainWindow)
        self.actionbalise1_del.setObjectName(u"actionbalise1_del")
        self.actiontrain0_config = QAction(MainWindow)
        self.actiontrain0_config.setObjectName(u"actiontrain0_config")
        self.actiontrain0_del = QAction(MainWindow)
        self.actiontrain0_del.setObjectName(u"actiontrain0_del")
        self.actiontrain1_config = QAction(MainWindow)
        self.actiontrain1_config.setObjectName(u"actiontrain1_config")
        self._2 = QAction(MainWindow)
        self._2.setObjectName(u"_2")
        self.actiontrain1_del = QAction(MainWindow)
        self.actiontrain1_del.setObjectName(u"actiontrain1_del")
        self.actiontrain1_config_2 = QAction(MainWindow)
        self.actiontrain1_config_2.setObjectName(u"actiontrain1_config_2")
        self.actionstation0_config = QAction(MainWindow)
        self.actionstation0_config.setObjectName(u"actionstation0_config")
        self.actionstation1_config = QAction(MainWindow)
        self.actionstation1_config.setObjectName(u"actionstation1_config")
        self.actionstation1_del = QAction(MainWindow)
        self.actionstation1_del.setObjectName(u"actionstation1_del")
        self.actionstation0_del = QAction(MainWindow)
        self.actionstation0_del.setObjectName(u"actionstation0_del")
        self.actionline_maxlength = QAction(MainWindow)
        self.actionline_maxlength.setObjectName(u"actionline_maxlength")
        self.actionreload_size = QAction(MainWindow)
        self.actionreload_size.setObjectName(u"actionreload_size")
        self.actionzoom_in = QAction(MainWindow)
        self.actionzoom_in.setObjectName(u"actionzoom_in")
        self.actionzoom_out = QAction(MainWindow)
        self.actionzoom_out.setObjectName(u"actionzoom_out")
        self.actionfollow = QAction(MainWindow)
        self.actionfollow.setObjectName(u"actionfollow")
        self.actionbalise0_local = QAction(MainWindow)
        self.actionbalise0_local.setObjectName(u"actionbalise0_local")
        self.actionbalise1_local = QAction(MainWindow)
        self.actionbalise1_local.setObjectName(u"actionbalise1_local")
        self.actionmap_draw = QAction(MainWindow)
        self.actionmap_draw.setObjectName(u"actionmap_draw")
        self.actionmap_view = QAction(MainWindow)
        self.actionmap_view.setObjectName(u"actionmap_view")
        self.actionabout = QAction(MainWindow)
        self.actionabout.setObjectName(u"actionabout")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        font = QFont()
        font.setKerning(True)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(False)
        self.run_widget = QWidget(self.centralwidget)
        self.run_widget.setObjectName(u"run_widget")
        self.run_widget.setGeometry(QRect(10, 10, 1261, 651))
        self.run_widget.setFont(font)
        self.run_widget.setAutoFillBackground(False)
        self.label_trains_speed = QLabel(self.centralwidget)
        self.label_trains_speed.setObjectName(u"label_trains_speed")
        self.label_trains_speed.setGeometry(QRect(30, 20, 461, 131))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setKerning(True)
        self.label_trains_speed.setFont(font1)
        self.label_trains_speed.setAlignment(
            Qt.AlignmentFlag.AlignLeading | Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignTop)
        self.statuslabel = QLabel(self.centralwidget)
        self.statuslabel.setObjectName(u"statuslabel")
        self.statuslabel.setGeometry(QRect(780, 50, 461, 21))
        self.statuslabel.setFont(font1)
        self.statuslabel.setAlignment(
            Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTop | Qt.AlignmentFlag.AlignTrailing)
        self.timelabel = QLabel(self.centralwidget)
        self.timelabel.setObjectName(u"timelabel")
        self.timelabel.setGeometry(QRect(780, 20, 461, 21))
        self.timelabel.setFont(font1)
        self.timelabel.setAlignment(
            Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignTop | Qt.AlignmentFlag.AlignTrailing)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 33))
        self.menu_file = QMenu(self.menubar)
        self.menu_file.setObjectName(u"menu_file")
        self.menu_balise = QMenu(self.menubar)
        self.menu_balise.setObjectName(u"menu_balise")
        self.menu_balise_list = QMenu(self.menu_balise)
        self.menu_balise_list.setObjectName(u"menu_balise_list")
        self.menubalise0 = QMenu(self.menu_balise_list)
        self.menubalise0.setObjectName(u"menubalise0")
        self.menubalise1 = QMenu(self.menu_balise_list)
        self.menubalise1.setObjectName(u"menubalise1")
        self.menu_train = QMenu(self.menubar)
        self.menu_train.setObjectName(u"menu_train")
        self.menu_train_list = QMenu(self.menu_train)
        self.menu_train_list.setObjectName(u"menu_train_list")
        self.menutrain0 = QMenu(self.menu_train_list)
        self.menutrain0.setObjectName(u"menutrain0")
        self.menu_run = QMenu(self.menubar)
        self.menu_run.setObjectName(u"menu_run")
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.menu_maps = QMenu(self.menubar)
        self.menu_maps.setObjectName(u"menu_maps")
        self.menu_station = QMenu(self.menubar)
        self.menu_station.setObjectName(u"menu_station")
        self.menu_station_list = QMenu(self.menu_station)
        self.menu_station_list.setObjectName(u"menu_station_list")
        self.menustation0 = QMenu(self.menu_station_list)
        self.menustation0.setObjectName(u"menustation0")
        self.menustation1 = QMenu(self.menu_station_list)
        self.menustation1.setObjectName(u"menustation1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_balise.menuAction())
        self.menubar.addAction(self.menu_train.menuAction())
        self.menubar.addAction(self.menu_station.menuAction())
        self.menubar.addAction(self.menu_run.menuAction())
        self.menubar.addAction(self.menu_maps.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menu_file.addAction(self.action_log_save)
        self.menu_file.addAction(self.action_config_save)
        self.menu_balise.addAction(self.menu_balise_list.menuAction())
        self.menu_balise.addAction(self.action_balise_create)
        self.menu_balise_list.addAction(self.menubalise0.menuAction())
        self.menu_balise_list.addAction(self.menubalise1.menuAction())
        self.menubalise0.addAction(self.actionbalise0_config)
        self.menubalise0.addAction(self.actionbalise0_del)
        self.menubalise0.addAction(self.actionbalise0_local)
        self.menubalise1.addAction(self.actionbalise1_config)
        self.menubalise1.addAction(self.actionbalise1_del)
        self.menubalise1.addAction(self.actionbalise1_local)
        self.menu_train.addAction(self.menu_train_list.menuAction())
        self.menu_train.addAction(self.action_train_create)
        self.menu_train_list.addAction(self.menutrain0.menuAction())
        self.menutrain0.addAction(self.actiontrain0_config)
        self.menutrain0.addAction(self.actiontrain0_del)
        self.menu_run.addAction(self.action_run)
        self.menu_run.addAction(self.action_stop)
        self.menu_run.addAction(self.action_pause)
        self.menu_run.addSeparator()
        self.menu_run.addAction(self.actionreload_size)
        self.menu_run.addAction(self.actionzoom_in)
        self.menu_run.addAction(self.actionzoom_out)
        self.menu_run.addAction(self.actionfollow)
        self.menu_help.addAction(self.actionabout)
        self.menu_maps.addAction(self.actionline_maxlength)
        self.menu_maps.addAction(self.actionmap_draw)
        self.menu_maps.addAction(self.actionmap_view)
        self.menu_station.addAction(self.menu_station_list.menuAction())
        self.menu_station.addAction(self.action_station_create)
        self.menu_station_list.addAction(self.menustation0.menuAction())
        self.menu_station_list.addAction(self.menustation1.menuAction())
        self.menustation0.addAction(self.actionstation0_config)
        self.menustation0.addAction(self.actionstation0_del)
        self.menustation1.addAction(self.actionstation1_config)
        self.menustation1.addAction(self.actionstation1_del)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(
            QCoreApplication.translate("MainWindow", u"\u5e94\u7b54\u5668\u8f66\u5e95\u4f20\u8f93\u4eff\u771f", None))
        self.action_balise_create.setText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa", None))
        self.action_balise_create.setIconText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa", None))
        self.action_log_save.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u5fd7\u4fdd\u5b58", None))
        self.action_config_save.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e\u4fdd\u5b58", None))
        self.action_train_create.setText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa", None))
        self.action_run.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb", None))
        self.action_stop.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u675f", None))
        self.action_pause.setText(QCoreApplication.translate("MainWindow", u"\u6682\u505c", None))
        self.action_station_create.setText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa", None))
        self.actionbalise0_config.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.actionbalise0_del.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.actionbalise1_config.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.actionbalise1_del.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.actiontrain0_config.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.actiontrain0_del.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.actiontrain1_config.setText(QCoreApplication.translate("MainWindow", u"train1_config", None))
        self._2.setText(QCoreApplication.translate("MainWindow", u"train1_config", None))
        self.actiontrain1_del.setText(QCoreApplication.translate("MainWindow", u"train1_del", None))
        self.actiontrain1_config_2.setText(QCoreApplication.translate("MainWindow", u"train1_config", None))
        self.actionstation0_config.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.actionstation1_config.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.actionstation1_del.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.actionstation0_del.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.actionline_maxlength.setText(QCoreApplication.translate("MainWindow", u"\u7ebf\u8def\u914d\u7f6e", None))
        self.actionreload_size.setText(
            QCoreApplication.translate("MainWindow", u"\u81ea\u9002\u5e94\u7a97\u53e3", None))
        self.actionzoom_in.setText(QCoreApplication.translate("MainWindow", u"\u653e\u5927\u7a97\u53e3", None))
        self.actionzoom_out.setText(QCoreApplication.translate("MainWindow", u"\u7f29\u5c0f\u7a97\u53e3", None))
        self.actionfollow.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u89d2\u8ddf\u8e2a", None))
        self.actionbalise0_local.setText(QCoreApplication.translate("MainWindow", u"\u5b9a\u4f4d", None))
        self.actionbalise1_local.setText(QCoreApplication.translate("MainWindow", u"\u5b9a\u4f4d", None))
        self.actionmap_draw.setText(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c\u8868\u7f16\u8f91", None))
        self.actionmap_view.setText(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c\u56fe\u9884\u89c8", None))
        self.actionabout.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.label_trains_speed.setText(QCoreApplication.translate("MainWindow", u"Train0 Speed\uff1a100km/h", None))
        self.statuslabel.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.timelabel.setText(QCoreApplication.translate("MainWindow", u"Time\uff1a2026-1-6 19:45:13", None))
        self.menu_file.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menu_balise.setTitle(QCoreApplication.translate("MainWindow", u"\u5e94\u7b54\u5668", None))
        self.menu_balise_list.setTitle(QCoreApplication.translate("MainWindow", u"\u5217\u8868", None))
        self.menubalise0.setTitle(QCoreApplication.translate("MainWindow", u"balise0", None))
        self.menubalise1.setTitle(QCoreApplication.translate("MainWindow", u"balise1", None))
        self.menu_train.setTitle(QCoreApplication.translate("MainWindow", u"\u5217\u8f66", None))
        self.menu_train_list.setTitle(QCoreApplication.translate("MainWindow", u"\u5217\u8868", None))
        self.menutrain0.setTitle(QCoreApplication.translate("MainWindow", u"CR400AF", None))
        self.menu_run.setTitle(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c", None))
        self.menu_help.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.menu_maps.setTitle(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c\u56fe", None))
        self.menu_station.setTitle(QCoreApplication.translate("MainWindow", u"\u8f66\u7ad9", None))
        self.menu_station_list.setTitle(QCoreApplication.translate("MainWindow", u"\u5217\u8868", None))
        self.menustation0.setTitle(QCoreApplication.translate("MainWindow", u"\u4e0a\u6d77\u5357", None))
        self.menustation1.setTitle(QCoreApplication.translate("MainWindow", u"\u4e0a\u6d77\u7ad9", None))
    # retranslateUi

